experiment_name: task3_fanar_jordanian

model:
  type: fanar
  name: QCRI/Fanar-1-9B
  cache_dir: /scratch/mk8737/huggingface
  offline: true

dataset:
  path: datasets/task3/jordanian.json
  instruction_path: prompts/task3-jordanian.txt

task:
  type: dialogue_completion
  max_tokens: 256

judge:
  prompt_path: prompts/judge-task3.txt

output:
  predictions_path: results/predictions/task3/jordanian/fanar.csv
  metrics_path: results/metrics/task3/jordanian/fanar.json
