experiment_name: task3_gemma3_27b_it_moroccan

model:
  type: gemma3_27b_it
  name: google/gemma-3-27b-it
  cache_dir: /scratch/mk8737/huggingface
  offline: true

dataset:
  path: datasets/task3/moroccan.json
  instruction_path: prompts/task3-moroccan.txt

task:
  type: dialogue_completion
  max_tokens: 256

judge:
  prompt_path: prompts/judge-task3.txt

output:
  predictions_path: results/predictions/task3/moroccan/gemma3_27b_it.csv
  metrics_path: results/metrics/task3/moroccan/gemma3_27b_it.json
