constants:
  model:
    type: fanar
    name: QCRI/Fanar-1-9B
    offline: true
  dataset: test
  task:
    name: task2
    type: answer_generation
    lang: ar

experiment_name: ${constants.task.name}_${constants.model.type}_oneshot_${constants.dataset}

model:
  type: ${constants.model.type}
  name: ${constants.model.name}
  cache_dir: /scratch/mk8737/huggingface
  offline: ${constants.model.offline}

dataset:
  path: datasets/answer-gen/${constants.dataset}.json
  instruction_path: prompts/${constants.task.name}_oneshot.txt

task:
  type: ${constants.task.type}
  lang: ${constants.task.lang}

judge:
  prompt_path: prompts/judge-task2.txt

output:
  predictions_path: results/predictions/${constants.task.name}/${constants.dataset}/${constants.model.type}_oneshot.csv
  metrics_path: results/metrics/${constants.task.name}/${constants.dataset}/${constants.model.type}_oneshot.json
