constants:
  model: 
    type: gpt52
    name: gpt-5.2
    max_tokens: 16 # this is hardset to 64 or 128 in the script, because below that, GPT API just returns nothing for most MCQs

  dataset: test
  task: 
    name: task1
    type: mcq

experiment_name: task1_${constants.model.type}

model:
  type: ${constants.model.type}            #model handler type as written in models/__init__.py
  name: ${constants.model.name}  # OpenAI model name, e.g. gpt-5
  # api_key: sk-...                  # optional; if omitted, OPENAI_API_KEY env var is used
  max_tokens: ${constants.model.max_tokens}


dataset:
  path: datasets/qa/${constants.dataset}.json   #path to dataset JSON file
  instruction_path: prompts/${constants.task.name}.txt  #path to instruction file (default.txt)

task:
  type: ${constants.task.type}                #task 1: mcq or task 2: answer_generation

output:
  predictions_path: results/predictions/${constants.task.name}/${constants.dataset}/${constants.model.type}.csv #specify output pred file
  metrics_path: results/metrics/${constants.task.name}/${constants.dataset}/${constants.model.type}.json  #specift output pred file
