experiment_name: task1_meditron_medarabench

model:
  type: meditron
  name: OpenMeditron/Meditron3-70B
  cache_dir: /scratch/mk8737/huggingface
  offline: true

dataset:
  path: datasets/qa/medarabench.json
  instruction_path: prompts/task1.txt

task:
  type: mcq

output:
  predictions_path: results/predictions/task1/medarabench/meditron.csv
  metrics_path: results/metrics/task1/medarabench/meditron.json
